version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Verify Setup
          command: |
            echo "CircleCI setup is working!"
            mkdir -p artifacts
            echo "This is a test file." > artifacts/test.txt
      - store_artifacts:
          path: artifacts
          destination: artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
